### ISSUE TITLE
Additional Features + UI/UX enhancements

### ISSUE THREAD

**Issue by diaasaur** [chingu-voyages/v46-tier2-team-14#17]
**__Feature Description__**
cool features :D

**__Major User Stories/tasks__**
- [ ] As a user, I want to have an option to change font and font size
- [x] As a user, I want to switch between light/dark mode.
- [ ] As a user, I want to be able to share the link to a recipe
- [ ] As a user, I want to be able to see a preview when I share the link for a recipe
- [ ] As a user, I should be able to filter the search/trending results based on tags
- [ ] As a user, I should be able to scroll to top of the recipes by clicking on scroll to top (⬆) button ( research the best way to represent this )
